# Generated by Django 4.2.6 on 2023-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blog_options_remove_blog_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='project',
            field=models.CharField(choices=[('0', 'Motors'), ('1', 'Creatives')], default='ABCD', max_length=50),
        ),
    ]
